# -*- coding: utf-8 -*-
"""DashboradJudson_Gabriel_Ferreira_dos_SantosPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11U8AtHcM4lbmJB8V-Bos930ge0QuRHRr

01. Setup
"""

!pip install -q gdown

import pandas as pd
import matplotlib.pyplot as plt
import gdown

"""02. Função de download

"""

def baixar_arquivo_google_drive(url, nome_arquivo):
    """
    Baixa um arquivo compartilhado do Google Drive
    e salva no ambiente do Google Colab.
    """

    gdown.download(url, nome_arquivo, quiet=False, fuzzy=True)

    print("Arquivo baixado com sucesso!")

"""3. Testando o download"""

url = "https://drive.google.com/file/d/1f6yG6cfStIiz5FJn2XsxM9EB1X7sWvSg/view?usp=sharing"
arquivo_csv = "alunos.csv"

baixar_arquivo_google_drive(url, arquivo_csv)

"""4. Função carregar_csv"""

def carregar_csv(nome_arquivo):
    """
    Lê o arquivo CSV e transforma os dados em um DataFrame.

    sep=";" indica que as colunas do arquivo estão separadas por ponto e vírgula.
    decimal="," indica que os números decimais usam vírgula.
    """

    df = pd.read_csv(nome_arquivo, sep=";", decimal=",")

    return df

"""5. Testando leitura"""

df = carregar_csv(arquivo_csv)

df.head()

"""6. Conferindo colunas"""

print(df.columns)

"""7. Função padronizar_colunas

"""

def padronizar_colunas(df):
    """
    Padroniza os nomes das colunas do DataFrame.

    A função remove espaços extras, coloca tudo em minúsculo,
    troca espaços por underline e remove alguns acentos comuns.
    """

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("ç", "c")
        .str.replace("ã", "a")
        .str.replace("á", "a")
        .str.replace("é", "e")
        .str.replace("í", "i")
        .str.replace("ó", "o")
        .str.replace("ú", "u")
    )

    return df

"""8. Testando padronização"""

print("Antes:")
print(df.columns)

df = padronizar_colunas(df)

print("\nDepois:")
print(df.columns)

"""9. Função converter_notas_para_numero"""

def converter_notas_para_numero(df):
    """
    Converte as colunas de notas para valores numéricos.

    Caso algum valor esteja com vírgula decimal, como "8,5",
    a função troca a vírgula por ponto antes da conversão.
    """

    colunas_notas = ["atividade_1", "prova_1", "atividade_2", "prova_2"]

    for coluna in colunas_notas:
        df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

    return df

"""10. Testando conversão"""

df = converter_notas_para_numero(df)

df[["atividade_1", "prova_1", "atividade_2", "prova_2"]].head()

"""11. Conferindo tipos dos dados"""

df[["atividade_1", "prova_1", "atividade_2", "prova_2"]].dtypes

"""12. Função calcular_nota_final_e_situacao"""

def calcular_nota_final_e_situacao(df):
    """
    Calcula a nota final e define a situação do aluno.

    Regra usada:
    nota_final = prova_1 + atividade_1 + prova_2 + atividade_2

    Se nota_final for maior ou igual a 70, o aluno está aprovado.
    Caso contrário, está reprovado.
    """

    df["nota_final"] = (
        df["prova_1"] +
        df["atividade_1"] +
        df["prova_2"] +
        df["atividade_2"]
    )

    df["situacao"] = df["nota_final"].apply(
        lambda nota: "Aprovado" if nota >= 70 else "Reprovado"
    )

    return df

"""13. Testando cálculo da situação"""

df = calcular_nota_final_e_situacao(df)

df[[
    "matricula",
    "aluno",
    "atividade_1",
    "prova_1",
    "atividade_2",
    "prova_2",
    "nota_final",
    "situacao"
]].head()

"""14. Função calcular_indicadores"""

def calcular_indicadores(df):
    """
    Calcula os principais indicadores da turma.
    """

    indicadores = {
        "total_alunos": len(df),
        "total_aprovados": len(df[df["situacao"] == "Aprovado"]),
        "total_reprovados": len(df[df["situacao"] == "Reprovado"]),
        "media_geral": df["nota_final"].mean(),
        "maior_nota": df["nota_final"].max(),
        "menor_nota": df["nota_final"].min()
    }

    return indicadores

"""15. Função exibir_indicadores"""

def exibir_indicadores(indicadores):
    """
    Exibe os indicadores da turma de forma organizada.
    """

    print("===== DASHBOARD DA TURMA =====")
    print(f"Total de alunos: {indicadores['total_alunos']}")
    print(f"Aprovados: {indicadores['total_aprovados']}")
    print(f"Reprovados: {indicadores['total_reprovados']}")
    print(f"Média geral da turma: {indicadores['media_geral']:.2f}")
    print(f"Maior nota: {indicadores['maior_nota']:.2f}")
    print(f"Menor nota: {indicadores['menor_nota']:.2f}")

"""16. Testando indicadores"""

indicadores = calcular_indicadores(df)

print(indicadores)

exibir_indicadores(indicadores)

"""17. Função grafico_situacao"""

def grafico_situacao(df):
    """
    Cria um gráfico de barras mostrando a quantidade de alunos
    aprovados e reprovados.
    """

    situacao_contagem = df["situacao"].value_counts()

    plt.figure(figsize=(6, 4))
    situacao_contagem.plot(kind="bar")

    plt.title("Quantidade de alunos por situação")
    plt.xlabel("Situação")
    plt.ylabel("Quantidade de alunos")
    plt.xticks(rotation=0)
    plt.show()

"""teste - Gráfico de situação"""

grafico_situacao(df)

"""18. Função grafico_distribuicao_notas"""

def grafico_distribuicao_notas(df):
    """
    Cria um histograma mostrando a distribuição das notas finais.
    """

    plt.figure(figsize=(8, 4))

    df["nota_final"].plot(kind="hist", bins=10)

    plt.title("Distribuição das notas finais")
    plt.xlabel("Nota final")
    plt.ylabel("Quantidade de alunos")
    plt.show()

"""teste - Histograma"""

grafico_distribuicao_notas(df)

"""19. Função grafico_medias_avaliacoes"""

def grafico_medias_avaliacoes(df):
    """
    Cria um gráfico de barras mostrando a média da turma
    em cada avaliação.
    """

    medias_avaliacoes = df[[
        "atividade_1",
        "prova_1",
        "atividade_2",
        "prova_2"
    ]].mean()

    plt.figure(figsize=(7, 4))

    medias_avaliacoes.plot(kind="bar")

    plt.title("Média da turma por avaliação")
    plt.xlabel("Avaliação")
    plt.ylabel("Média")
    plt.xticks(rotation=0)
    plt.show()

"""teste - Médias por avaliação"""

grafico_medias_avaliacoes(df)

"""20. Função gerar_ranking"""

def gerar_ranking(df):
    """
    Ordena os alunos pela nota final, do maior para o menor.
    """

    ranking = df.sort_values(by="nota_final", ascending=False)

    return ranking[["matricula", "aluno", "nota_final", "situacao"]]

"""teste - Ranking"""

ranking = gerar_ranking(df)

ranking.head(10)

"""21. Função grafico_top10_aluno"""

def grafico_top10_alunos(df):
    """
    Cria um gráfico com os 10 alunos que tiveram as maiores notas finais.
    """

    ranking = df.sort_values(by="nota_final", ascending=False)

    top10 = ranking.head(10)

    plt.figure(figsize=(10, 5))

    plt.barh(top10["aluno"], top10["nota_final"])

    plt.title("Top 10 alunos com maiores notas")
    plt.xlabel("Nota final")
    plt.ylabel("Aluno")
    plt.gca().invert_yaxis()
    plt.show()

"""teste - Gráfico top 10"""

grafico_top10_alunos(df)

"""final - Execução completa"""

url = "https://drive.google.com/file/d/1f6yG6cfStIiz5FJn2XsxM9EB1X7sWvSg/view?usp=sharing"
arquivo_csv = "alunos.csv"

baixar_arquivo_google_drive(url, arquivo_csv)

df = carregar_csv(arquivo_csv)

df = padronizar_colunas(df)

df = converter_notas_para_numero(df)

df = calcular_nota_final_e_situacao(df)

display(df[[
    "matricula",
    "aluno",
    "atividade_1",
    "prova_1",
    "atividade_2",
    "prova_2",
    "nota_final",
    "situacao"
]].head())

indicadores = calcular_indicadores(df)
exibir_indicadores(indicadores)

grafico_situacao(df)
grafico_distribuicao_notas(df)
grafico_medias_avaliacoes(df)

ranking = gerar_ranking(df)
display(ranking)

grafico_top10_alunos(df)

"""Tudo junto e misturado"""

import pandas as pd
import matplotlib.pyplot as plt
import gdown


def baixar_arquivo_google_drive(url, nome_arquivo):
    """
    Baixa um arquivo compartilhado do Google Drive
    e salva no ambiente do Google Colab.
    """

    gdown.download(url, nome_arquivo, quiet=False, fuzzy=True)

    print("Arquivo baixado com sucesso!")


def carregar_csv(nome_arquivo):
    """
    Lê o arquivo CSV e transforma os dados em um DataFrame.
    """

    df = pd.read_csv(nome_arquivo, sep=";", decimal=",")

    return df


def padronizar_colunas(df):
    """
    Padroniza os nomes das colunas do DataFrame.
    """

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("ç", "c")
        .str.replace("ã", "a")
        .str.replace("á", "a")
        .str.replace("é", "e")
        .str.replace("í", "i")
        .str.replace("ó", "o")
        .str.replace("ú", "u")
    )

    return df


def converter_notas_para_numero(df):
    """
    Converte as colunas de notas para valores numéricos.
    """

    colunas_notas = ["atividade_1", "prova_1", "atividade_2", "prova_2"]

    for coluna in colunas_notas:
        df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

    return df


def calcular_nota_final_e_situacao(df):
    """
    Calcula a nota final e define a situação do aluno.
    """

    df["nota_final"] = (
        df["prova_1"] +
        df["atividade_1"] +
        df["prova_2"] +
        df["atividade_2"]
    )

    df["situacao"] = df["nota_final"].apply(
        lambda nota: "Aprovado" if nota >= 70 else "Reprovado"
    )

    return df


def calcular_indicadores(df):
    """
    Calcula os principais indicadores da turma.
    """

    indicadores = {
        "total_alunos": len(df),
        "total_aprovados": len(df[df["situacao"] == "Aprovado"]),
        "total_reprovados": len(df[df["situacao"] == "Reprovado"]),
        "media_geral": df["nota_final"].mean(),
        "maior_nota": df["nota_final"].max(),
        "menor_nota": df["nota_final"].min()
    }

    return indicadores


def exibir_indicadores(indicadores):
    """
    Exibe os indicadores da turma de forma organizada.
    """

    print("===== DASHBOARD DA TURMA =====")
    print(f"Total de alunos: {indicadores['total_alunos']}")
    print(f"Aprovados: {indicadores['total_aprovados']}")
    print(f"Reprovados: {indicadores['total_reprovados']}")
    print(f"Média geral da turma: {indicadores['media_geral']:.2f}")
    print(f"Maior nota: {indicadores['maior_nota']:.2f}")
    print(f"Menor nota: {indicadores['menor_nota']:.2f}")


def grafico_situacao(df):
    """
    Cria um gráfico de barras mostrando a quantidade de alunos
    aprovados e reprovados.
    """

    situacao_contagem = df["situacao"].value_counts()

    plt.figure(figsize=(6, 4))
    situacao_contagem.plot(kind="bar")

    plt.title("Quantidade de alunos por situação")
    plt.xlabel("Situação")
    plt.ylabel("Quantidade de alunos")
    plt.xticks(rotation=0)
    plt.show()


def grafico_distribuicao_notas(df):
    """
    Cria um histograma mostrando a distribuição das notas finais.
    """

    plt.figure(figsize=(8, 4))

    df["nota_final"].plot(kind="hist", bins=10)

    plt.title("Distribuição das notas finais")
    plt.xlabel("Nota final")
    plt.ylabel("Quantidade de alunos")
    plt.show()


def grafico_medias_avaliacoes(df):
    """
    Cria um gráfico de barras mostrando a média da turma
    em cada avaliação.
    """

    medias_avaliacoes = df[[
        "atividade_1",
        "prova_1",
        "atividade_2",
        "prova_2"
    ]].mean()

    plt.figure(figsize=(7, 4))

    medias_avaliacoes.plot(kind="bar")

    plt.title("Média da turma por avaliação")
    plt.xlabel("Avaliação")
    plt.ylabel("Média")
    plt.xticks(rotation=0)
    plt.show()


def gerar_ranking(df):
    """
    Ordena os alunos pela nota final, do maior para o menor.
    """

    ranking = df.sort_values(by="nota_final", ascending=False)

    return ranking[["matricula", "aluno", "nota_final", "situacao"]]


def grafico_top10_alunos(df):
    """
    Cria um gráfico com os 10 alunos que tiveram as maiores notas finais.
    """

    ranking = df.sort_values(by="nota_final", ascending=False)

    top10 = ranking.head(10)

    plt.figure(figsize=(10, 5))

    plt.barh(top10["aluno"], top10["nota_final"])

    plt.title("Top 10 alunos com maiores notas")
    plt.xlabel("Nota final")
    plt.ylabel("Aluno")
    plt.gca().invert_yaxis()
    plt.show()


url = "https://drive.google.com/file/d/1f6yG6cfStIiz5FJn2XsxM9EB1X7sWvSg/view?usp=sharing"
arquivo_csv = "alunos.csv"

baixar_arquivo_google_drive(url, arquivo_csv)

df = carregar_csv(arquivo_csv)
df = padronizar_colunas(df)
df = converter_notas_para_numero(df)
df = calcular_nota_final_e_situacao(df)

display(df[[
    "matricula",
    "aluno",
    "atividade_1",
    "prova_1",
    "atividade_2",
    "prova_2",
    "nota_final",
    "situacao"
]].head())

indicadores = calcular_indicadores(df)
exibir_indicadores(indicadores)

grafico_situacao(df)
grafico_distribuicao_notas(df)
grafico_medias_avaliacoes(df)

ranking = gerar_ranking(df)
display(ranking)

grafico_top10_alunos(df)

"""Respondendo - Tarefa 04"""

#Respondendo a primeria questão:
print(f"Média geral: {indicadores['media_geral']:.2f}") #Média geral da turma

#Respondendo a segunda questão:
print(f"Maior média: {indicadores['maior_nota']:.2f}") #A maior média da sala

#Respondendo a terceira questão:
print(f"Menor média: {indicadores['menor_nota']:.2f}") #A menor média da sala

#transforma as datas e, dados passivéis de manipulação
df['data_de_nascimento'] = pd.to_datetime(df['data_de_nascimento'], format='%d/%m/%Y') #transforma a data de nascimento em dados

#Respondendo a quarta questão:
indice_mais_velho = df['data_de_nascimento'].idxmin() #procurar a pessoa mais velha
aluno_mais_velho = df.loc[indice_mais_velho] #pega a linha inteira da pessoa, para pegar todas as informações
print(f"Aluno mais velho: {aluno_mais_velho['aluno']}; E sua media: {aluno_mais_velho['nota_final']:.2f}") #Exibe a pessoa mais velha e sua média

#Respondendo a quinta questão:
indice_mais_novo = df['data_de_nascimento'].idxmax() #procurar a pessoa mais nova
aluno_mais_novo = df.loc[indice_mais_novo] #pega a linha inteira da pessoa, para pegar todas as informações
print(f"Aluno mais novo: {aluno_mais_novo['aluno']}; E sua media: {aluno_mais_novo['nota_final']:.2f}") #Exibe a pessoa mais nova e sua média